const CREATE = "CREATE";
const FETCH_ALL = "FETCH_ALL";
const DELETE = "DELETE";
const UPDATE = "UPDATE";
const LIKE_POST = "LIKE_POST";
const AUTH = "AUTH";
const LOGOUT = "LOGOUT";

export { CREATE, FETCH_ALL, DELETE, UPDATE, LIKE_POST, AUTH, LOGOUT };
