const CREATE = "CREATE";
const FETCH_ALL = "FETCH_ALL";
const DELETE = "DELETE";
const UPDATE = "UPDATE";
const LIKE_POST = "LIKE_POST";
const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
const START_LOADING = "START_LOADING";
const END_LOADING = "END_LOADING";

export {
  CREATE,
  FETCH_ALL,
  DELETE,
  UPDATE,
  LIKE_POST,
  AUTH,
  LOGOUT,
  FETCH_BY_SEARCH,
  START_LOADING,
  END_LOADING,
};
